[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.17.0"

[[constraint]]
  name = "github.com/dutchcoders/goftp"
  branch = "master"